# The world's simplest Makefile
default:	computeParallelPeptideComposition

computePeptideComposition: computePeptideComposition.c
	gcc -o computePeptideComposition computePeptideComposition.c

computeParalelPeptideComposition: computeParallelPeptideComposition.c
	gcc -o computeParallelPeptideComposition computeParallelPeptideComposition.c -lpthread
